### ISSUE TITLE
Watch-lessc crashes on file change

### ISSUE THREAD

**Issue by andrewowen** [jccovey/watch-lessc#4]
After changing my less file to import a new file, I received this error:

```
watch-lessc -i less/template-001.less -o css/style.css 
watch-lessc: Updated: /Users/andrewowen/Sites/Product Shop/Startup Framework/Developer/samples/template/css/style.css
/usr/local/lib/node_modules/watch-lessc/node_modules/less/lib/less/parser/parser.js:117
            imports.contents[fileInfo.filename] = str;
                   ^
TypeError: Cannot read property 'contents' of undefined
    at Object.Parser.parse (/usr/local/lib/node_modules/watch-lessc/node_modules/less/lib/less/parser/parser.js:117:20)
    at /usr/local/lib/node_modules/watch-lessc/app.js:43:16
    at fs.js:334:14
    at FSReqWrap.oncomplete (fs.js:95:15)
```

**Comment by electricSemyon** [comment]
I have the same problem.

**Comment by buzzyboy** [comment]
I have the same problem as well.

**Comment by jccovey** [comment]
Please update watch-lessc via NPM - I fixed a package.json discrepancy and published a new version to the NPM registry. 

This error was caused by an API change in the less compiler between 1.75 and 2.x (I never updated this library to use the new 2.x method).
